### PR TITLE
Documentation changes

### PR DESCRIPTION
**Pull request by mitzkia**
Back ported 2 documentation changes to master branch

### CODE REVIEW

**Comment by ihrwein** [comment]
Please add the commit `aac4d97d01cb38ce4dd3cf7477a9d06f800b2f31` to the PR, too.

**Comment by ihrwein** [comment]
:+1:
@lbudai Do you want to review it (just patch ports)?

**Comment by lbudai** [comment]
No, thanks :)

**Comment by ihrwein** [comment]
Thanks!

**Pull request merged**
